# Generated by Django 3.2 on 2021-08-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FizzBuzzRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("int1", models.IntegerField()),
                ("int2", models.IntegerField()),
                ("limit", models.IntegerField()),
                ("string1", models.CharField(max_length=200)),
                ("string2", models.CharField(max_length=200)),
            ],
        ),
    ]
